### ISSUE TITLE
Car looks weird ingame

### ISSUE THREAD

**Issue by umustbeloggedintododat** [Parik27/DragonFF#129]
The parts(bonnet, doors,wheel,windscreen) are small 
The model is rotated wrong, even when changing it.
Why is this happening?
![image](https://user-images.githubusercontent.com/54049600/147890954-33eb08a7-97f3-4f53-9a1c-bd3a7d7c6cd4.png)

**Comment by umustbeloggedintododat** [comment]
Fixed, I just had to apply transformations.

**Comment by ThePortuguesePlayer** [comment]
No, not closed. I think an important feature to request is for a checkbox at export (on by default) to apply all transformations automatically prior to export, because this stuff is easy to miss and will make you hunt for what is wrong part by part.
Another problem is DFFs that were exported with transformations unapplied, be it either out of DragonFF or out of KAM's in 3DS, don't import with the correct scale when imported with this addon, while it works fine when importing back in KAM's or Zmodeler. DragonFF's importer completely discards the object scaling data at DFF import, so you don't even have the chance of applying the transformations and export again.

**Comment by Parik27** [comment]
@ThePortuguesePlayer Not sure why or when it doesn't happen, but it is supposed to happen. I exported the default cube with a scale, and re-imported it and it did have the correct scale after importing it back.

**Comment by ThePortuguesePlayer** [comment]
Holy c... You are right. I didn't know this was fixed, it was one of my major frustrations back in older versions, so much I had 3DS and KAM's installed exclusively to fix this. Well, then, thanks very much!
