### ISSUE TITLE
weird shades, destroyed model

### ISSUE THREAD

**Issue by rvfs0n** [Parik27/DragonFF#147]
When i export model from blender and i want import it again weird shade appears. In game (MTA:SA) model is glitched. 
Larger models are crashing down, walls are shifting, or the ceiling is buried, someone can help? I do not know what to do.

![image](https://user-images.githubusercontent.com/104649446/166061603-4d8f1037-4c3c-4323-ba55-e52edb37ec66.png)
![image](https://user-images.githubusercontent.com/104649446/166061150-ff08d41a-2ae7-44fa-8606-2bdd2359b373.png)

**Comment by Parik27** [comment]
Use the new-export branch (https://github.com/Parik27/DragonFF/tree/new-export)

**Comment by ThePortuguesePlayer** [comment]
These are buildings. They don't use normals. It's normal that when you import these models that the shading looks strange, as Blender had to make up normal vectors out of thin air, in a sense. Just ignore the shading by setting your viewport shading to Flat.
The distortion issues you are having ingame are probably due to unapplied transformations on the objects. Select your objects (in object mode) and press Ctrl+A to apply Scale and Rotation. In the object panel, DragonFF - Export Object tab, make sure you have Export Normals disabled, both vertex colors enabled (you have to paint these) and only UV1 enabled (you can only make use of UV2 ingame using a custom shader).
