### ISSUE TITLE
Color Attributes Problem

### ISSUE THREAD

**Issue by ElWonder666** [Parik27/DragonFF#177]
when I open a pre-made gta sa object, the color attributes come as face Corner > byte color and I have to redo the whole pre light by hand, it's not coming as vertex>color and this ends up causing a problem because gta doesn't recognizes as custom vertex colors

How can i fix it, without remade?

**Comment by Parik27** [comment]
I added face corner and byte color support to the exporter. You should be able to use both vertex > color and face corner > byte color and it should work as expected. You can update to the latest version and check if it works fine now.

I have also added clarification for why this was an issue and how it was fixed in the commit message.

**Comment by ElWonder666** [comment]
Wow Thank you mate, i will test soon
