### ISSUE TITLE
Texture lighting issue

### ISSUE THREAD

**Issue by ToddCarson44** [Parik27/DragonFF#193]
I have UV mapped an entire vehicle and was apply the new UV to it, But it doesn't emit the game lighting as the LVPD car does.
![image](https://user-images.githubusercontent.com/111051725/197826827-5a653a08-cb72-4251-a45e-9bfd12142230.png)

**Comment by ToddCarson44** [comment]
Ive already matched the DragonFF - Export Material as it was on the original vehicle texture

**Comment by ThePortuguesePlayer** [comment]
Do you have an second UV map on?
If yes, you can also try to disable "Modulate Material Color" on all the objects (DragonFF tab in object settings). I don't know what that option even does, since it has no documentation entry, but in the past I've seen disabling this option helps when my exported models appear overly dark ingame, as shown in the examples.
![image](https://user-images.githubusercontent.com/47691365/198159137-565ebd94-ad9c-4fad-97a0-a1cfb19500ce.png)
![image](https://user-images.githubusercontent.com/47691365/198159155-63ab9a3a-8a38-48ec-b684-a67f62f0e678.png)
