### ISSUE TITLE
Warning: Multiple Meshes with same Atomic index. Export will be invalid

### ISSUE THREAD

**Issue by EthanBoiLol** [Parik27/DragonFF#214]
Hi, while using the addon I am having an issue that sometimes happens when importing a model from _Spongebob Battle For Bikini Bottom_ and _The Spongebob Squarepants Movie Game_.

what's odd is that some models from the game work, while others don't, what can I do to avoid this?

**Comment by Psycrow101** [comment]
@EthanBoiLol Added support for this case for your game. Raw and poorly tested.
https://github.com/Psycrow101/DragonFF/tree/multi-mesh

![image](https://user-images.githubusercontent.com/31922454/229343334-491b8bb9-04de-40ae-a2e7-5e80c0e5a84b.png)

**Comment by Calvin-rgb** [comment]
> @EthanBoiLol Added support for this case for your game. Raw and poorly tested. https://github.com/Psycrow101/DragonFF/tree/multi-mesh
> 
> ![image](https://user-images.githubusercontent.com/31922454/229343334-491b8bb9-04de-40ae-a2e7-5e80c0e5a84b.png)

I don't understand a bit, in which cases it is better to use this script branch? When there is a lot of geometry in the scene?

**Comment by Psycrow101** [comment]
DragonFF is currently trying to merge meshes into one if Atomics have the same Frame index.
![image](https://user-images.githubusercontent.com/31922454/229351149-2ea9ab03-15e5-4fd1-addc-8c84614a0a68.png)

As a result, only one Atomic is exported after import. In my branch, in this case, instead of merging meshes, several are created, which are inherited as children from the first mesh.

Import behavior in main branch:
![image](https://user-images.githubusercontent.com/31922454/229351306-a59e96fe-4ee6-4870-b2ff-4d226b3a0b9f.png)


Import behavior in multi-mesh branch:
![image](https://user-images.githubusercontent.com/31922454/229351268-9e34959c-a80f-428c-a49d-0fc3ed150d56.png)

**Comment by Parik27** [comment]
@Psycrow101 I haven't had a look at the code, but how does it work? How does it keep track of these objects? If it uses the parents to do so, would that cause issues with models which already have a parent in the DFF file (say GTA vehicle/ped models)?

**Comment by Psycrow101** [comment]
@Parik27 Unfortunately, so far I'm not handling models with inheritance correctly. Didn't figure out how to group them for such cases.
