### ISSUE TITLE
Normals getting messed up

### ISSUE THREAD

**Issue by eatthew** [Parik27/DragonFF#218]
Hey,

having issues after exporting to .dff. Some normals are getting messed up despite looking good in blender. 
Blender version 3.4.1

![image](https://user-images.githubusercontent.com/65094360/229570955-a30602ac-6d60-4e80-9516-ac6445a7da66.png)
![image](https://user-images.githubusercontent.com/65094360/229571057-0edf895a-a9a9-4bf0-8594-50209b3f56f5.png)

![image](https://user-images.githubusercontent.com/65094360/229571104-ac234948-b583-48b7-afbf-4ef381fad85b.png)
![image](https://user-images.githubusercontent.com/65094360/229571159-e30e2cf9-6df6-4a1e-b360-56881ecff725.png)

**Comment by Calvin-rgb** [comment]
Try to select these polygons, then press Alt + N -> Reset Vectors
Or the tab "Object Data Properties" ->Geometric data -> Clear user data on separation normals

**Comment by eatthew** [comment]
Already tried, none of these helps.

**Comment by Calvin-rgb** [comment]
With what parameters are you importing the model?

**Comment by eatthew** [comment]
I'm not importing, just exporting with standard checks. 
![image](https://user-images.githubusercontent.com/65094360/229625823-2de8b1cc-9e38-49bb-bc77-d38f40cabfff.png)

**Comment by Calvin-rgb** [comment]
That is, the model was made by you?
If so, then you forgot to put the Edge Split modifier

**Comment by eatthew** [comment]
Yes, and edge split is there. The other side of the car looks normal tho.

**Comment by Calvin-rgb** [comment]
Then with such a problem it is better to turn to @Parik27

**Comment by ThePortuguesePlayer** [comment]
I've been dealing with this problem for years now.
For starters, make sure you have the latest version.
The cause of this problem is probably in the UVs. Select the affected faces in Edit Mode and make sure their UV islands are not separated (on both UV maps). You will have to actually select the vertices and move them to make sure everything is connected and not just overlapping. You will see you will probably find that your vertices are separated from each other. You will have to merge them. Merge all your overlapping vertices.
DFF files don't support more than one UV vector per vertex, so what happens is that the exporter is separating any vertex whose UV is at more than 1 place at a time, but then it doesn't assign the correct normals to them (this is a bug).

**Comment by Parik27** [comment]
From what I can tell, after exporting and re-importing, there's no noticeable difference in the normals or vertices of the two models (the original and the exported). So the exporter is not exporting faulty normals.

**Comment by eatthew** [comment]
What's the problem then? Blender itself?

**Comment by Parik27** [comment]
Well, it's most likely the model. I'm not sure what your desired result is. You can try editing the model's normals manually if it gives you better lighting.

**Comment by eatthew** [comment]
I don't get it how it can be the model since it's mirrored and left quarterpanel seems totally fine yet the right side is messed up.

**Comment by Parik27** [comment]
I'll look into it further. It's possible that the importer 'fixes' the normals while importing.

**Comment by Parik27** [comment]
Okay, it does seem to be an issue with the exporter. For now what you can do is the following:

1. Export your model to a dff file
2. Import it with the "Import custom normals" option deselected
3. Export it again

**Comment by eatthew** [comment]
Gonna check it on Monday as I'm away right now.
