### ISSUE TITLE
Seat panel for editing vertex color

### ISSUE THREAD

**Issue by MarkHollywood** [Parik27/DragonFF#29]
Hi, I wanted to offer a life hack for my beloved addon. I’m tired of going into the “Vertex Color” tab to edit the color of the vertex and everything related to it. You can put this in a separate panel DragonFF, with all the necessary buttons. I think this is not difficult to do, just group the ready-made functions into one panel for greater convenience. Thank's!

**Comment by Parik27** [comment]
The vertex colour tab? :thinking:

**Comment by MarkHollywood** [comment]
I'm talking about the tab with the settings of the object, where the list of color of vertices is. @Parik27

**Comment by Parik27** [comment]
Sorry I don't know what tab you're talking about, a screenshot would be helpful.

**Comment by MarkHollywood** [comment]
![image](https://user-images.githubusercontent.com/29834790/71642247-8ab39280-2cd2-11ea-9076-6969fcec496d.png)
I messed up the names of the tabs a bit, sorry

**Comment by swift502** [comment]
When does DragonFF require you to use vertex colors?

What exactly are you doing with them @MarkHollywood ?

**Comment by MarkHollywood** [comment]
Nothing new. I wanted to simplify editing the color of the vertices of the object with the help of a new panel in the add-on, where all the necessary buttons were located, and not gently climb the entire program to edit the color of the vertices. A big waste of time. @swift502

**Comment by swift502** [comment]
As far as I was concerned, vertex painting isn't at all in the scope of this addon. DFF import has nothing to do with vertex painting in Blender. Which is why I was wondering what specifically are you using vertex paint for that's closely related to DFF import?

Also, 

> all the necessary buttons

There's two buttons right? Add vertex color, and remove vertex color... Are the two buttons what you wish was in a different tab somewhere?

![image](https://user-images.githubusercontent.com/24359130/71645231-7b821400-2cd5-11ea-82c1-62e7b8707a97.png)

Please bear with us, we're just trying to understand what you mean specifically. 🙂

**Comment by Parik27** [comment]
Yeah, it would be out of scope for the project to do that. And even if it were, it would make no sense to move those setting to somewhere where they don't fit, the options in Blender are categorised for a reason. You can't just have vertex settings in the material, for example.

**Comment by MarkHollywood** [comment]
I use vertex colors to edit the lighting of an object. I understood your answer, I just use a lot of functions related to the color of the vertices (editing, coloring) and I just wanted to put it all in a separate place. I got it.

**Comment by swift502** [comment]
I find the vertex paint mode quite good. I also worked on custom lighting when I was converting Liberty City to BeamNG and had no problems with it.
