### ISSUE TITLE
Item rpGEOMETRILIGHT flag breaks the render

### ISSUE THREAD

**Issue by Calvin-rgb** [Parik27/DragonFF#298]
I encountered a problem: I exported a map object (small landscape) and encountered a problem with the model “blinking”, I tried KAM scripts, and everything was fine there
Then, for testing, I turned off Enable Lighting in the export parameters, and all the problems disappeared
Is it possible to disable this feature by default?

**Comment by Parik27** [comment]
Lighting depends on the type of model you're exporting. Ped and vehicle models for instance, you'll have to enable lighting. But map models are prelit and they need it to be disabled or else game will keep flickering between the two modes. 

It takes the setting from the model you're importing. Can't really disable it by default since it'll break the other models.
