### ISSUE TITLE
Exported cars have the camera higher than vanilla's

### ISSUE THREAD

**Issue by ThePortuguesePlayer** [Parik27/DragonFF#31]
Hi again!
This is a new issue that came with the collision exporter update, but I think it's the importer that causes it.
Basically, this is how the camera should be at, at this position like in the vanilla game:
![proxy_sa 2020-03-14 22-34-41-45 avi_snapshot_00 00 078](https://user-images.githubusercontent.com/47691365/76692678-a7b0fe00-6651-11ea-9f93-48b6d07bd7fc.jpg)

The moment I simply import a car and export it back again, ingame, the camera shifts up, like so:
![proxy_sa 2020-03-14 23-50-40-91](https://user-images.githubusercontent.com/47691365/76692690-e6df4f00-6651-11ea-9d0d-26edd8bce5e6.png)

(While having this version, if I use blend files that had the car imported by old pre-col-exporter versions of DragonFF, the camera doesn't change.)

How can I solve this?

**Comment by ThePortuguesePlayer** [comment]
(Ah, if I make a blend file with a car imported with the current version of the addon, and Append the collisions from that file to the one whose collisions were imported with an older version, the camera shifts up from then on. Just extra info from experiments I've been making about this.)

**Comment by Parik27** [comment]
Yeah the collision bounds calculations in the latest version are a bit broken. Someone else reported this issue as well, and I'm yet to look into it

**Comment by ThePortuguesePlayer** [comment]
Are there bad effects if I use the importer script from an old version?
What can be made to solve this while a proper fix doesn't come?

**Comment by Parik27** [comment]
Yeah, there shouldn't be any bad effects from an old version, no. I'll look into a fix later today

**Comment by ThePortuguesePlayer** [comment]
Thank you!

**Comment by LeXDDD** [comment]
Hi. I've been asked to look into issue aswell, so far i figured out the reason why it's happen. ColMesh object of any car model have 8 extra vertices imported, and 2 of them - at the bottom of the model. When collision gets calculated it still keeping in mind all of theese, but listed above issue itself, appears because of the bottom two vertices, that's why there's offset in camera. Earlier versions of importer do that aswell, might be because original model has them in the first place. Here's the screenshot of imported Sultan model. If bottom two vertices deleted, everything seems to be fixed.
![scr](https://user-images.githubusercontent.com/62285061/76845940-c204fa80-6850-11ea-901a-395778ba9287.jpg)

**Comment by Parik27** [comment]
Hmm, that seems interesting. The old version didn't export the collision model (just imported it), it took everything from the old model which is why the previous version works. I'll look into why the extra vertices are created. I thought it was an error with the Collision Bounds calculation, but if removing those vertices fixes it, I guess that's not the issue then.

Thanks for your help!

**Comment by ThePortuguesePlayer** [comment]
This has been confirmed to fix the camera issue!

![proxy_sa 2020-03-17 19-20-57-93](https://user-images.githubusercontent.com/47691365/76894994-12974a80-6887-11ea-9b7f-86eaf6ca0cd8.png)

Impressive how, to my side, this was so simple to fix. It may sound stupid how I kept missing those for months, and it is, but I never once edited the collisions in Vertex view mode, I kept looking at them in Edge and Face modes so the vertices were invisible to me the whole time.
I guess this reinforces the importance of having a fresh pair of eyes come in when you are stuck with certain issues. My man, you are awesome! Thank you once again.

**Comment by ThePortuguesePlayer** [comment]
(I won't close this just yet so it stays visible while a fix for the importer doesn't come.)

**Comment by Parik27** [comment]
Alright, I've addressed this issue in fbb85b00498489157d780e38073816002dfde6b9, could you confirm that fixed it?

**Comment by ThePortuguesePlayer** [comment]
From what I can see in Blender, this has solved it. Many thanks!
I don't have the availability to make an ingame test so soon, but I trust that everything seems fine. I tell if anything happens to go wrong. If I don't say anything, it's because everything went fine, eh eh.
Have a nice day. I'll be closing this now.
