### ISSUE TITLE
GTA LCS Map Import and Some Feedback

### ISSUE THREAD

**Issue by vollkorn2** [Parik27/DragonFF#49]
Hello Parik, 
I'm using your Tool for a year now and i just found a way to Import GTA LCS IPLs with it. But it only works with the GTA: ReLCS Mod for VC. In this Mod is the full Map and Vehicels Convertet to the Normal DFF File so your tool is accepting it for Importing without issues. But to use the IPLs and IDEs of this Mod you have to copy the whole Map Folder of the Original Vice City into this Standalone Mod-game and then replace and rename some IPLs of the Original IPLs. 
As Example: 
IPL/IDE commer copied into the airport folder. Delete Original IPL and IDE and rename both commer Files to airport so your IPL importer is accepting it.
This is not working 100% but the Most Models will be Importet and Placed Correctly but some are placed wrong or are missing. Textures are working too with Magic TXD.
Maybe you can Implement this in your tool to make the whole process easier.

I had a Second Problem long ago when Installing the Plug-In: It's not possible for me to install the newest version of your Plug-in but i could fix this by using an older version (DragonFF v.0.0.2) and replacing all Files with the new ones.

And I also found out that the newest version can't Import GTA III Map as correctly as the Special BeamNG.drive DragonFF Tool from Swifterk. (Maybe I should try this later for LCS)
Also the SA Map isn't Importet 100% correctly but I found another tool for that. GTA Tools for SA (Blender 2.79)

A big thanks to you and Swifterik for helping me Importing the full GTA III and VC Map!

**Comment by swift502** [comment]
Hi!

I kinda regret that I left the LCS and VCS IPL/IDE lists in the addon, because I only later realised that it's really hard to find those (originally PSP) files properly converted to their PC equivalent formats.

If we found a mod that 100% converts all LCS assets to dff and txd, we could maybe settle on that version, because from what I've seen, every mod (there seems to be a few) has a different approach to porting LCS (and VCS) to PC, and only some of them even bother with converting the files.

But the map importer is marked as experimental / incomplete for exactly this reason. And I'm not sure @Parik27 wants to tackle improving / extending the map importer in the near future. I unfortunately certainly don't plan on contributing to this in the near future.

> can't Import GTA III Map as correctly as the Special BeamNG.drive DragonFF Tool from Swifterk
You still have that branch? Better keep it because I already deleted it on my account. 😄
I can't think of any major improvements I made, other than fixing #13, which however wasn't a clean fix, but rather a duct tape solution which probably shouldn't generally be used, hence it's not in this repo.

> Also the SA Map isn't Importet 100% correctly
I'm curious what exactly is wrong there? It should work just fine. I never thoroughly tested it thought.

**Comment by vollkorn2** [comment]
Thanks for the fast answer, just like you did on YouTube  :D

Ok, so we need to keep an eye on that. 

You're right. Maybe they shouldn't be listed but Maybe you could write in the ReadMe file a short Explaination on how the Import (via Mods) should work. 

Why did you delete it? It worked fine!

With San Andreas there was a few Problems with Missing objects like in San Fierro where not even the Half of the city was Importet. But I can't tell you exactly because I switched very soon to the other Tool.

**Comment by swift502** [comment]
> write in the ReadMe file a short Explaination on how the Import (via Mods) should work

I agree, maybe a wiki page? I can't promise to do it myself though. I don't plan to contribute to this repo anymore. I just keep an eye on any map importer related questions.

> Why did you delete it? It worked fine!

I was done using it... 😃
