### ISSUE TITLE
Txd export and import

### ISSUE THREAD

**Issue by leminial** [Parik27/DragonFF#88]
Будет ли обновление аддона ?
Очень нужны функции экспорта и импорта текстур .txd
Я даже готов заплатить
------‐----------------
Will there be an update to the addon? The functions of import and import of .txd textures are very much needed I'm even willing to pay

**Comment by Izzotop** [comment]
What about Magic.TXD ?07:29, May 3, 2021, leminial ***@***.***>:
Будет ли обновление аддона ?
Очень нужны функции экспорта и импорта текстур .txd
Я даже готов заплатить
------‐----------------
Will there be an update to the addon? The functions of import and import of .txd textures are very much needed I'm even willing to pay

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
-- Sent from Yandex.Mail for mobile

**Comment by leminial** [comment]
Yes, I use it
But it takes a long time for me, it is not convenient
Loading textures into Blender and creating materials for them, as well as then also collecting them into a .txd file
In general, I decided to speed up my work in Blender.

**Comment by Skyliner77** [comment]
Так а зачем создавать новые материалы? Можно очень легко залить все текстуры на модель, просто открываешь 
File -> External Data -> Find missing files [https://imgur.com/a/9ds0BGZ]. Указываешь папку с текстурами и они на место становятся. 
Конечно с TXD импортёром было бы намного легче, но пока что только так. Можешь ему в ЛС попробовать постучатся, думаю от лишней деньги не откажется.

**Comment by leminial** [comment]
Это я знаю
Я знаю как восстановить текстуры для модели
Вопрос в другом совсем
Как быстро загрузить текстуру без создания материала вручную и т.д.
Думаю ему сегодня на почту написать

ср, 5 мая 2021 г., 10:44 Skyliner77 ***@***.***>:

**Comment by leminial** [comment]
Срочно нужна помощь, я испытываю эффект Мандела и мне страшно
Почему аддон называется DragonFF если он назывался всегда DragonDFF и ник
разработчика был Patrik27 а не Parik27

ср, 5 мая 2021 г. в 10:44, Skyliner77 ***@***.***>:

**Comment by Izzotop** [comment]
March 9 @ 5:43 pm
![image](https://user-images.githubusercontent.com/1680033/143482213-d8f3e4fe-2e54-4efb-8d41-6121718937d0.png)

**Comment by Psycrow101** [comment]
TXD import is already implemented. Export is not planned because Blender interface is not designed for this
